[general]
import = [
  # import common config
  "~\\dotfiles\\terminals\\alacritty\\common.toml",
  "~\\dotfiles\\terminals\\alacritty\\keybindings.toml",
  # import themes
  "~\\dotfiles\\terminals\\alacritty\\themes\\dracula.toml"
]

[terminal]

[terminal.shell]
program = "C:\\Windows\\System32\\wsl.exe"
